export const PRODUCTS = [
  {
    id: 0,
    name: "White Sneakers",
    image: "img/shoesOne.jpg",
    featured: true,
    description: "Lightweight white sneakers",
    price: "$70.00",
  },
  {
    id: 1,
    name: "Red Nikes",
    image: "img/shoesTwo.jpg",
    featured: true,
    description: "Red Nike Freeruns",
    price: "$85.00",
  },
  {
    id: 2,
    name: "White-Orange Nikes",
    image: "img/shoesThree.jpg",
    featured: true,
    description: "White & Orange Nike Sneakers",
    price: "$70.00",
  },
  {
    id: 3,
    name: "Tan Boots",
    image: "img/shoesFour.jpg",
    description: "Tan colored Boots",
    featured: true,
    price: "$70.00",
  },
  {
    id: 4,
    name: "New Balance Sneakers",
    image: "img/shoesFive.jpg",
    featured: true,
    description: "Light Pastel Colored New Balance Sneakers",
    price: "$85.00",
  },
  {
    id: 5,
    name: "Jordans",
    image: "img/shoesSix.jpg",
    featured: true,
    description: "White and Black Jordan High tops",
    price: "$90.00",
  },
  {
    id: 6,
    name: "Green Vans",
    image: "img/shoesSeven.jpg",
    featured: true,
    description: "Bright Green Colored Vans",
    price: "$85.00",
  },
  {
    id: 7,
    name: "Red and Black Converse",
    image: "img/shoesEight.jpg",
    featured: true,
    description: "Red and Black Leather Converse",
    price: "$80.00",
  },
  {
    id: 5,
    name: "Jordans",
    image: "img/shoesSix.jpg",
    featured: true,
    description: "White and Black Jordan High tops",
    price: "$90.00",
  },
  {
    id: 6,
    name: "Green Vans",
    image: "img/shoesSeven.jpg",
    featured: true,
    description: "Bright Green Colored Vans",
    price: "$85.00",
  },
  {
    id: 7,
    name: "Red and Black Converse",
    image: "img/shoesEight.jpg",
    featured: true,
    description: "Red and Black Leather Converse",
    price: "$80.00",
  },
  {
    id: 5,
    name: "Jordans",
    image: "img/shoesSix.jpg",
    featured: true,
    description: "White and Black Jordan High tops",
    price: "$90.00",
  },

];